[package]
name = "tiny-evm"
version = "0.1.0"
authors = ["Patricio Palladino <email@patriciopalladino.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/alcuadrado/tiny-evm"

[dependencies]
num_enum = "0.5.0"
ethereum-types = "0.9.2"
hex = "0.4"
sha3 = "0.9.0"
